#!/bin/bash
# Reset ALL password settings and use trust
sudo -u postgres psql -c "ALTER SYSTEM RESET password_encryption;" 2>/dev/null
# Clear postgresql.auto.conf completely
sudo bash -c 'echo "# Do not edit this file manually!" > /var/lib/postgresql/18/main/postgresql.auto.conf'
sudo bash -c 'echo "# It will be overwritten by the ALTER SYSTEM command." >> /var/lib/postgresql/18/main/postgresql.auto.conf'

# Ensure pg_hba.conf is trust
PG_HBA="/etc/postgresql/18/main/pg_hba.conf"
sudo tee $PG_HBA > /dev/null << 'EOF'
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust
host    all             all             0.0.0.0/0               trust
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust
EOF

sudo pg_ctlcluster 18 main restart
sleep 2
echo "TRUST_MODE_RESTORED"
