apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cancercare-ingress
  namespace: cancercare360
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - app.cancercare360.com
      secretName: cancercare-tls-secret
  rules:
    - host: app.cancercare360.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cancercare-backend
                port:
                  number: 3001
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: cancercare-frontend
                port:
                  number: 3000
